//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Competence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competence()
        {
            this.Freelancer_Competence = new HashSet<Freelancer_Competence>();
        }
    
        public int Id { get; set; }
        public int RoleId { get; set; }
        [DisplayName("Kompetens")]
        public string CompetenceName { get; set; }    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Freelancer_Competence> Freelancer_Competence { get; set; }
    }
}
