//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FreelancerEntities : DbContext
    {
        public FreelancerEntities()
            : base("name=FreelancerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Competence> Competence { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Freelancer_Competence> Freelancer_Competence { get; set; }
        public virtual DbSet<FreelancerPerson> FreelancerPerson { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<OtherInfo> OtherInfo { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Work> Work { get; set; }
    }
}
