//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Work
    {
        public int Id { get; set; }
        public int FreelancerId { get; set; }
        [DisplayName("Roll")]
        public string Role { get; set; }
        [DisplayName("Företag")]
        public string Company { get; set; }
        [DisplayName("Startdatum")]
        public System.DateTime StartDate { get; set; }
        [DisplayName("Slutdaum")]
        public Nullable<System.DateTime> EndDate { get; set; }
        [DisplayName("Arbetsbeskrivning")]
        public string WorkDescription { get; set; }
    
        public virtual FreelancerPerson FreelancerPerson { get; set; }
    }
}
